import type { Device } from "./roboticsMonitoringDashboardTypes"
import type { RoboticsMonitoringDashboardProps } from "./roboticsMonitoringDashboardTypes"

export const demoDevices: Device[] = [
  {
    id: "RBX-1042",
    name: "Forklift A-12",
    site: "Site Alpha",
    model: "XR-Fork v3",
    status: "Online",
    battery: 78,
    temperature: 46,
    lastSeenMinutes: 0,
    emergency: false,
    errorRate: 0.6,
  },
  {
    id: "RBX-1077",
    name: "Picker P-07",
    site: "Site Alpha",
    model: "XR-Pick v2",
    status: "Warning",
    battery: 18,
    temperature: 58,
    lastSeenMinutes: 0,
    emergency: false,
    errorRate: 2.9,
  },
  {
    id: "RBX-1120",
    name: "Conveyor C-03",
    site: "Site Beta",
    model: "XR-Conv v1",
    status: "Offline",
    battery: 41,
    temperature: 39,
    lastSeenMinutes: 27,
    emergency: false,
    errorRate: 1.2,
  },
  {
    id: "RBX-1189",
    name: "AMR M-19",
    site: "Site Beta",
    model: "XR-AMR v4",
    status: "Error",
    battery: 54,
    temperature: 73,
    lastSeenMinutes: 0,
    emergency: true,
    errorRate: 7.6,
  },
  {
    id: "RBX-1214",
    name: "Inspection I-04",
    site: "Site Gamma",
    model: "XR-Vision v2",
    status: "Maintenance",
    battery: 92,
    temperature: 44,
    lastSeenMinutes: 0,
    emergency: false,
    errorRate: 0.4,
  },
  {
    id: "RBX-1299",
    name: "Palletizer PL-02",
    site: "Site Gamma",
    model: "XR-Pal v1",
    status: "Online",
    battery: 66,
    temperature: 51,
    lastSeenMinutes: 0,
    emergency: false,
    errorRate: 1.1,
  },
]

export const roboticsMonitoringDashboardDefaults: RoboticsMonitoringDashboardProps =
  {
    language: "ko",
    enableChat: true,
    chatTitle: "운영 분석 채팅",
    chatPlaceholder: "질문을 입력하세요… (예: 오프라인 장비 요약)",
    title: "Robotics Monitoring",
    subtitle:
      "Real-time fleet health, alerts, and diagnostics across sites",
    devices: demoDevices,
    groupBySite: true,
    enableRealtimeSimulation: true,
    refreshMs: 900,
    showKPIs: true,
    showFilters: true,
    showSearch: true,
    showDetailPanel: true,
    filterOffline: false,
    filterLowBattery: false,
    filterAbnormalTemp: false,
    filterEmergency: false,
    lowBatteryThreshold: 20,
    abnormalTempThreshold: 65,
    initialSelectedId: "RBX-1042",
    background: "#0B141A",
    panelBackground: "#0F1E27",
    cardBackground: "#0D1A22",
    borderColor: "#19303B",
    textPrimary: "#E8F1F6",
    textSecondary: "#8FA6B2",
    accent: "#2ED3B7",
    statusOnline: "#2ED3B7",
    statusOffline: "#5E7482",
    statusWarning: "#FFB020",
    statusError: "#FF4D6D",
    statusMaintenance: "#8A6CFF",
    headingFont: {
      fontFamily: "system-ui, sans-serif",
      fontSize: 22,
      fontWeight: 600,
      letterSpacing: "-0.03em",
      lineHeight: "1.2em",
    },
    bodyFont: {
      fontFamily: "system-ui, sans-serif",
      fontSize: 14,
      fontWeight: 500,
      letterSpacing: "-0.01em",
      lineHeight: "1.35em",
    },
    monoFont: {
      fontFamily:
        "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
      fontSize: 12,
      letterSpacing: "-0.01em",
      lineHeight: "1.2em",
    },
  }
