import type { RoboticsMonitoringDashboardProps } from "./roboticsMonitoringDashboardTypes"

export const roboticsMonitoringDashboardDefaults: RoboticsMonitoringDashboardProps =
  {
    language: "ko",
    enableChat: true,
    chatTitle: "운영 분석 채팅",
    chatPlaceholder: "질문을 입력하세요… (예: 오프라인 장비 요약)",
    title: "로봇 운영 모니터링",
    subtitle: "사이트별 실시간 상태, 알림, 진단 대시보드",
    devices: [],
    groupBySite: true,
    enableRealtimeSimulation: true,
    refreshMs: 900,
    showKPIs: true,
    showFilters: true,
    showSearch: true,
    showDetailPanel: true,
    filterOffline: false,
    filterLowBattery: false,
    filterAbnormalTemp: false,
    filterEmergency: false,
    lowBatteryThreshold: 20,
    abnormalTempThreshold: 65,
    initialSelectedId: "",
    background: "#0B141A",
    panelBackground: "#0F1E27",
    cardBackground: "#0D1A22",
    borderColor: "#19303B",
    textPrimary: "#E8F1F6",
    textSecondary: "#8FA6B2",
    accent: "#2ED3B7",
    statusOnline: "#2ED3B7",
    statusOffline: "#5E7482",
    statusWarning: "#FFB020",
    statusError: "#FF4D6D",
    statusMaintenance: "#8A6CFF",
    headingFont: {
      fontFamily: "system-ui, sans-serif",
      fontSize: 22,
      fontWeight: 600,
      letterSpacing: "-0.03em",
      lineHeight: "1.2em",
    },
    bodyFont: {
      fontFamily: "system-ui, sans-serif",
      fontSize: 14,
      fontWeight: 500,
      letterSpacing: "-0.01em",
      lineHeight: "1.35em",
    },
    monoFont: {
      fontFamily:
        "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
      fontSize: 12,
      letterSpacing: "-0.01em",
      lineHeight: "1.2em",
    },
  }
