services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - "1883:1883"

  db:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: robotops
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  simulator:
    build: ../simulator
    container_name: simulator
    environment:
      MQTT_HOST: mqtt
      MQTT_PORT: "1883"
      SITE_ID: "SeoulLine1"
      ROBOTS: "30"
      RATE: "1"
      QOS: "1"
    depends_on:
      - mqtt

volumes:
  pgdata:
