services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - "1883:1883"

  db:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: robotops
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  simulator:
    build: ../simulator
    container_name: simulator
    environment:
      MQTT_HOST: mqtt
      MQTT_PORT: "1883"
      SITE_ID: "SeoulLine1"
      ROBOTS: "30"
      RATE: "1"
      QOS: "1"
    depends_on:
      - mqtt

  backend:
    build: ../backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/robotops
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      MQTT_BROKER_URL: tcp://mqtt:1883
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mqtt
      - redis
  

volumes:
  pgdata:
