server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/robotops}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always

app:
  mqtt:
    brokerUrl: ${MQTT_BROKER_URL:tcp://mqtt:1883}